INSERT INTO vehicles (name, type, brand, model, year, seats, color,
    price_per_day, currency, district, pickup_location,
    driver_included, airport_transfer, available,
    driver_name, driver_phone, driver_languages,
    description, rating, review_count, category,
    created_at, updated_at)
VALUES
('Colombo City Tuk-Tuk', 'TUKTUK', 'Bajaj', 'RE', 2022, 3, 'Yellow',
    15.00, 'USD', 'Colombo', 'Colombo Fort',
    true, false, true,
    'Kamal Silva', '+94771234567', 'English, Sinhala',
    'Reliable tuk-tuk service around Colombo city', 4.5, 120, 'LOCAL',
    NOW(), NOW()),

('Airport Transfer Van', 'VAN', 'Toyota', 'HiAce', 2021, 8, 'White',
    45.00, 'USD', 'Colombo', 'BIA Katunayake Airport',
    true, true, true,
    'Nimal Perera', '+94777654321', 'English, Sinhala, Tamil',
    'Comfortable airport transfer van with AC', 4.8, 85, 'STANDARD',
    NOW(), NOW()),

('Kandy Hill Country Car', 'CAR', 'Toyota', 'Prius', 2020, 4, 'Silver',
    35.00, 'USD', 'Kandy', 'Kandy City Center',
    true, false, true,
    'Sunil Fernando', '+94765432109', 'English, Sinhala',
    'Comfortable car for hill country exploration', 4.6, 67, 'STANDARD',
    NOW(), NOW()),

('Ella Adventure Jeep', 'SUV', 'Jeep', 'Wrangler', 2019, 5, 'Green',
    55.00, 'USD', 'Badulla', 'Ella Town',
    true, false, true,
    'Roshan Dias', '+94712345678', 'English',
    'Perfect for Ella Rock and Nine Arch Bridge tours', 4.9, 43, 'PREMIUM',
    NOW(), NOW()),

('Galle Southern Tuk-Tuk', 'TUKTUK', 'Bajaj', 'RE', 2023, 3, 'Blue',
    12.00, 'USD', 'Galle', 'Galle Fort',
    true, false, true,
    'Priya Cooray', '+94723456789', 'English, Sinhala',
    'Best tuk-tuk for Galle Fort and southern coast', 4.4, 98, 'LOCAL',
    NOW(), NOW()),

('Colombo Luxury SUV', 'SUV', 'Toyota', 'Land Cruiser', 2022, 6, 'Black',
    85.00, 'USD', 'Colombo', 'Colombo 03',
    true, false, true,
    'Asanka Mendis', '+94734567890', 'English, Sinhala',
    'Premium SUV for luxury travel around Sri Lanka', 4.7, 32, 'LUXURY',
    NOW(), NOW()),

('Mirissa Beach Scooter', 'SCOOTER', 'Honda', 'Wave', 2021, 2, 'Red',
    18.00, 'USD', 'Matara', 'Mirissa Beach',
    false, false, true,
    NULL, NULL, NULL,
    'Self-drive scooter perfect for coastal exploration', 4.3, 156, 'ECONOMY',
    NOW(), NOW()),

('Sigiriya Cultural Van', 'MINIVAN', 'Toyota', 'KDH', 2020, 10, 'White',
    60.00, 'USD', 'Matale', 'Sigiriya Rock',
    true, false, true,
    'Chaminda Rathnayake', '+94745678901', 'English, Sinhala, Japanese',
    'Perfect for cultural triangle tours', 4.8, 54, 'STANDARD',
    NOW(), NOW());