INSERT INTO vehicles (name, type, brand, model, year, seats, color,
    price_per_day, currency, district, pickup_location,
    driver_included, airport_transfer, available,
    driver_name, driver_phone, driver_languages,
    description, rating, review_count, category,
    created_at, updated_at)
SELECT * FROM (VALUES
    ('Colombo City Tuk-Tuk', 'TUKTUK', 'Bajaj', 'RE', 2022, 3, 'Yellow',
        15.00, 'USD', 'Colombo', 'Colombo Fort',
        true, false, true,
        'Kamal Silva', '+94771234567', 'English, Sinhala',
        'Reliable tuk-tuk service around Colombo city', 4.5, 120, 'LOCAL',
        NOW(), NOW()),
    ('Airport Transfer Van', 'VAN', 'Toyota', 'HiAce', 2021, 8, 'White',
        45.00, 'USD', 'Colombo', 'BIA Katunayake Airport',
        true, true, true,
        'Nimal Perera', '+94777654321', 'English, Sinhala, Tamil',
        'Comfortable airport transfer van with AC', 4.8, 85, 'STANDARD',
        NOW(), NOW()),
    ('Kandy Hill Country Car', 'CAR', 'Toyota', 'Prius', 2020, 4, 'Silver',
        35.00, 'USD', 'Kandy', 'Kandy City Center',
        true, false, true,
        'Sunil Fernando', '+94765432109', 'English, Sinhala',
        'Comfortable car for hill country exploration', 4.6, 67, 'STANDARD',
        NOW(), NOW()),
    ('Ella Adventure Jeep', 'SUV', 'Jeep', 'Wrangler', 2019, 5, 'Green',
        55.00, 'USD', 'Badulla', 'Ella Town',
        true, false, true,
        'Roshan Dias', '+94712345678', 'English',
        'Perfect for Ella Rock and Nine Arch Bridge tours', 4.9, 43, 'PREMIUM',
        NOW(), NOW()),
    ('Galle Southern Tuk-Tuk', 'TUKTUK', 'Bajaj', 'RE', 2023, 3, 'Blue',
        12.00, 'USD', 'Galle', 'Galle Fort',
        true, false, true,
        'Priya Cooray', '+94723456789', 'English, Sinhala',
        'Best tuk-tuk for Galle Fort and southern coast', 4.4, 98, 'LOCAL',
        NOW(), NOW()),
    ('Colombo Luxury SUV', 'SUV', 'Toyota', 'Land Cruiser', 2022, 6, 'Black',
        85.00, 'USD', 'Colombo', 'Colombo 03',
        true, false, true,
        'Asanka Mendis', '+94734567890', 'English, Sinhala',
        'Premium SUV for luxury travel around Sri Lanka', 4.7, 32, 'LUXURY',
        NOW(), NOW()),
    ('Mirissa Beach Scooter', 'SCOOTER', 'Honda', 'Wave', 2021, 2, 'Red',
        18.00, 'USD', 'Matara', 'Mirissa Beach',
        false, false, true,
        NULL, NULL, NULL,
        'Self-drive scooter perfect for coastal exploration', 4.3, 156, 'ECONOMY',
        NOW(), NOW()),
    ('Sigiriya Cultural Van', 'MINIVAN', 'Toyota', 'KDH', 2020, 10, 'White',
        60.00, 'USD', 'Matale', 'Sigiriya Rock',
        true, false, true,
        'Chaminda Rathnayake', '+94745678901', 'English, Sinhala, Japanese',
        'Perfect for cultural triangle tours', 4.8, 54, 'STANDARD',
        NOW(), NOW())
) AS new_data (name, type, brand, model, year, seats, color,
    price_per_day, currency, district, pickup_location,
    driver_included, airport_transfer, available,
    driver_name, driver_phone, driver_languages,
    description, rating, review_count, category,
    created_at, updated_at)
WHERE NOT EXISTS (SELECT 1 FROM vehicles LIMIT 1);


INSERT INTO events (title, description, category, region, location,
    start_date, end_date, is_recurring, created_at)
SELECT * FROM (VALUES
    ('Vesak Festival',
     'Sri Lanka largest Buddhist festival celebrating the birth, enlightenment and passing of Lord Buddha. Lanterns and pandols lit across the island.',
     'FESTIVAL', 'Island-wide', 'Colombo',
     '2026-05-12'::date, '2026-05-13'::date, true, NOW()),
    ('Esala Perahera',
     'Grand procession of the Temple of the Tooth Relic in Kandy. Elephants, drummers, fire dancers in spectacular parade.',
     'FESTIVAL', 'Kandy', 'Kandy',
     '2026-08-03'::date, '2026-08-13'::date,true, NOW()),
    ('Sinhala and Tamil New Year',
     'Traditional Sri Lankan New Year celebrated by both Sinhalese and Tamil communities with rituals, games and special foods.',
     'FESTIVAL', 'Island-wide', 'Colombo',
     '2026-04-13'::date, '2026-04-14'::date,true, NOW()),
    ('Thai Pongal',
     'Tamil harvest festival giving thanks to the Sun God. Traditional Pongal dish cooked and celebrations with kolam drawings.',
     'RELIGIOUS', 'Jaffna', 'Jaffna',
     '2026-01-14'::date, '2026-01-15'::date, true, NOW()),
    ('Kataragama Festival',
     'Major religious festival at the Kataragama temple complex attended by Buddhist, Hindu, Muslim and indigenous Vedda devotees.',
     'RELIGIOUS', 'Kataragama', 'Kataragama',
     '2026-07-28'::date, '2026-08-06'::date, true, NOW()),
    ('Elephant Gathering — Minneriya',
     'One of the largest gatherings of wild Asian elephants in the world. Hundreds of elephants congregate at Minneriya Tank.',
     'WILDLIFE', 'Minneriya', 'Minneriya',
     '2026-07-01'::date, '2026-09-30'::date, true, NOW()),
    ('Whale Watching Season — Mirissa',
     'Peak season for blue whale and sperm whale sightings off the southern coast of Sri Lanka. Best months November to April.',
     'WILDLIFE', 'Mirissa', 'Mirissa',
     '2026-11-01'::date, '2027-04-30'::date, true, NOW()),
    ('Arugam Bay Surf Season',
     'World-class surf season at Arugam Bay. Attracts international surfers. Main Point and Whiskey Point are top surf spots.',
     'SURF', 'Arugam Bay', 'Arugam Bay',
     '2026-05-01'::date, '2026-10-31'::date, true, NOW()),
    ('Galle Literary Festival',
     'International literary festival held inside the historic Galle Fort. Authors, speakers and cultural events.',
     'ENTERTAINMENT', 'Galle', 'Galle',
     '2026-01-20'::date, '2026-01-24'::date, true, NOW()),
    ('Colombo Food Festival',
     'Annual food festival showcasing Sri Lankan cuisine, street food, and international dishes in Colombo.',
     'FOOD', 'Colombo', 'Colombo',
     '2026-03-15'::date, '2026-03-17'::date,true, NOW()),
    ('Southwest Monsoon',
     'Southwest monsoon brings heavy rainfall to western and southern coastal areas and hill country. Best to visit east coast during this period.',
     'MONSOON', 'West and South Coast', 'West and South Coast',
     '2026-05-01'::date, '2026-09-30'::date,true, NOW()),
    ('Northeast Monsoon',
     'Northeast monsoon affects northern and eastern coastal areas. Best to visit west and south coast during this period.',
     'MONSOON', 'North and East Coast', 'North and East Coast',
     '2026-10-01'::date, '2027-01-31'::date,true, NOW()),
    ('Diwali — Festival of Lights',
     'Hindu festival of lights celebrated by Tamil community across Sri Lanka with oil lamps, fireworks and sweets.',
     'RELIGIOUS', 'Island-wide', 'Island-wide',
     '2026-10-20'::date, '2026-10-20'::date, true, NOW()),
    ('Christmas in Galle Fort',
     'Unique Christmas celebrations inside the historic Galle Fort with decorations, events and festive markets.',
     'FESTIVAL', 'Galle', 'Galle',
     '2026-12-24'::date, '2026-12-26'::date,true, NOW()),
    ('Hikkaduwa Coral Festival',
     'Annual festival celebrating the coral reef ecosystem of Hikkaduwa. Snorkeling, diving events and beach activities.',
     'ENTERTAINMENT', 'Hikkaduwa', 'Hikkaduwa',
     '2026-03-01'::date, '2026-03-03'::date, true, NOW())
)AS new_data (title, description, category, region, location,
    start_date, end_date, is_recurring, created_at)
WHERE NOT EXISTS (SELECT 1 FROM events LIMIT 1);


INSERT INTO hidden_gems (title, description, category, district,
    latitude, longitude, how_to_get_there, best_time, tips,
    approved, rating, review_count, created_at, updated_at)
SELECT * FROM (VALUES
    ('Jungle Beach',
     'A secluded beach near Unawatuna only accessible by boat or a jungle trek. Crystal clear water with no crowds.',
     'BEACH', 'Galle', 6.0089, 80.2491,
     'Take a boat from Unawatuna beach (10 min) or hike 30 min through jungle trail.',
     'November to April (dry season)', 'Bring snacks — no shops. Go early morning for calm water.',
     true, 4.8, 245, NOW(), NOW()),
    ('Hiriketiya Bay',
     'A horseshoe shaped bay hidden from the main road. Popular with surfers and digital nomads. Laid back vibe.',
     'BEACH', 'Matara', 5.9667, 80.5833,
     'From Dickwella town take a tuk-tuk heading south for 3km. Ask for Hiriketiya.',
     'October to April', 'Arrive before 8am for the best surf. Several good cafes nearby.',
     true, 4.7, 189, NOW(), NOW()),
    ('Ravana Ella Cave',
     'A lesser known cave near the Ravana Falls in Ella. According to legend this is where King Ravana kept Sita. Dramatic views.',
     'RUINS', 'Badulla', 6.8553, 81.0581,
     'From Ella town take the road towards Wellawaya. The cave is 2km from Ravana Falls — unmarked path on the right.',
     'January to August', 'Hire a local guide from Ella town for LKR 500. Wear good shoes.',
     true, 4.6, 134, NOW(), NOW()),
    ('Bambarakanda Waterfall',
     'Sri Lanka highest waterfall at 263 metres. Hidden in the Horton Plains region. Few tourists reach the base.',
     'WATERFALL', 'Nuwara Eliya', 6.7833, 80.8167,
     'Take the Haputale to Belihuloya road. Bambarakanda village is 3km off the main road. 45 min trek to base.',
     'March to May and October to November', 'Trek early morning before mist rolls in. Bring rain gear.',
     true, 4.9, 312, NOW(), NOW()),
    ('Yapahuwa Rock Fortress',
     'An ancient rock fortress rising 100 metres from the surrounding plain. Far less visited than Sigiriya but equally impressive.',
     'RUINS', 'Kurunegala', 7.8333, 80.3167,
     'Take the Colombo to Anuradhapura road. Turn at Maho junction — Yapahuwa is 10km from Maho.',
     'December to April', 'Arrive at opening time (7am) — you may have the whole place to yourself.',
     true, 4.5, 98, NOW(), NOW()),
    ('Ella Rock',
     'A challenging hike offering panoramic views of the Ella Gap and surrounding tea estates. More rewarding than Little Adams Peak.',
     'VIEWPOINT', 'Badulla', 6.8748, 81.0465,
     'Walk along the railway track from Ella station towards Demodara for 2km then follow the trail markers uphill.',
     'January to April', 'Start by 6am. Takes 3-4 hours return. No signboards — hire a guide.',
     true, 4.8, 421, NOW(), NOW()),
    ('Knuckles Cloud Forest',
     'A UNESCO designated cloud forest with unique biodiversity. Remote villages, leeches, mist and extraordinary scenery.',
     'VIEWPOINT', 'Matale', 7.4167, 80.8000,
     'From Kandy take the Matale road then turn towards Rattota. Arrange permits at the Forest Department office.',
     'February to April', 'Multi-day treks available. Register with the Forest Department. Leech socks essential.',
     true, 4.9, 167, NOW(), NOW()),
    ('Pigeon Island',
     'A tiny island near Trincomalee with some of Sri Lanka best coral reefs. Home to blacktip reef sharks.',
     'BEACH', 'Trincomalee', 8.5500, 81.2667,
     'Take a boat from Nilaveli Beach (10 min). Book through guesthouses in Nilaveli.',
     'April to September (east coast dry season)', 'Snorkeling only — no diving to protect coral. Bring underwater camera.',
     true, 4.7, 278, NOW(), NOW()),
    ('Mulkirigala Rock Temple',
     'A series of cave temples built into a dramatic granite outcrop. Far less visited than Dambulla but equally impressive.',
     'TEMPLE', 'Hambantota', 6.1167, 80.4667,
     'From Tangalle take the inland road towards Weeraketiya — Mulkirigala is 16km from Tangalle.',
     'Year round', 'Remove shoes before entering. Small entrance fee. Climb to the top for ocean views.',
     true, 4.6, 112, NOW(), NOW()),
    ('Pambahinna Village',
     'A traditional Sri Lankan village in the Knuckles range where time seems to have stopped. Homestays available.',
     'VILLAGE', 'Matale', 7.4500, 80.8333,
     'Arrange through Kandy guesthouses. 4WD vehicle required. 3 hour journey from Kandy.',
     'February to April', 'Book homestay in advance. Bring cash — no ATMs. Respect local customs.',
     true, 4.8, 56, NOW(), NOW()),
    ('Secret Tea Estate Cafe — Nuwara Eliya',
     'A hidden cafe inside a working tea estate with panoramic mountain views. Serves single origin tea picked that morning.',
     'CAFE', 'Nuwara Eliya', 6.9500, 80.7833,
     'Ask locals in Nuwara Eliya for the Lovers Leap estate road. 4km from town centre on an unmarked road.',
     'Year round — best during flush season March to May', 'No sign outside. Ring the bell. LKR 200 for tea and biscuits.',
     true, 4.9, 89, NOW(), NOW()),
    ('Udawatta Kele Forest Sanctuary',
     'A forgotten royal forest reserve in the heart of Kandy city. Ancient trees, monkeys and complete silence despite being central.',
     'VIEWPOINT', 'Kandy', 7.2967, 80.6414,
     'Enter from Kandy city centre near the Temple of the Tooth — follow signs to the forest reserve entrance.',
     'Year round', 'Enter before 8am for bird watching. Bring insect repellent. Carry water.',
     true, 4.4, 203, NOW(), NOW()),
    ('Rathnapura Gem Mines',
     'Visit a working traditional gem mine in the gem capital of Sri Lanka. Watch miners sift for sapphires and rubies.',
     'VILLAGE', 'Ratnapura', 6.6833, 80.4000,
     'From Ratnapura town hire a tuk-tuk to the Elapatha area — ask for gem pit visits.',
     'Year round — avoid monsoon May to September', 'Negotiate entry fee directly with mine owner. LKR 500-1000.',
     true, 4.5, 145, NOW(), NOW()),
    ('Mangrove Safari — Madu River',
     'A boat journey through a vast mangrove ecosystem near Balapitiya. Ancient temples on islands, monitor lizards and birds.',
     'VILLAGE', 'Galle', 6.2833, 80.0500,
     'Take the coastal road between Colombo and Galle. Balapitiya town is 90km from Colombo — boats leave from the river bank.',
     'November to April', 'Morning boats have best wildlife. 2 hour tour. Bargain the boat price.',
     true, 4.6, 334, NOW(), NOW()),
    ('Ambuluwawa Tower',
     'A unique biodiversity complex with a spiral tower on a mountain top offering 360 degree views across four provinces.',
     'VIEWPOINT', 'Kandy', 7.1833, 80.5833,
     'From Gampola town (20km from Kandy) take the road up Ambuluwawa mountain — 6km of winding road.',
     'Year round — clearest views December to April', 'Climb the narrow spiral tower for views. LKR 200 entry.',
     true, 4.7, 267, NOW(), NOW())
) AS new_data (title, description, category, district,
    latitude, longitude, how_to_get_there, best_time, tips,
    approved, rating, review_count, created_at, updated_at)
WHERE NOT EXISTS (SELECT 1 FROM hidden_gems LIMIT 1);

INSERT INTO tour_guides (full_name, bio, languages, specialties,
    district, price_per_day, verified, available,
    rating, review_count, phone, email,
    created_at, updated_at)
SELECT * FROM (VALUES
    ('Kamal Bandara',
     'Expert wildlife guide with 12 years experience in Yala and Wilpattu. Excellent tracker with deep knowledge of Sri Lanka wildlife.',
     'English,Sinhala', 'WILDLIFE,PHOTOGRAPHY',
     'Hambantota', 65.00, true, true, 4.9, 234,
     '+94771234567', 'kamal.guide@gmail.com', NOW(), NOW()),
    ('Priya Perera',
     'Cultural heritage specialist based in Kandy. Expert in Buddhist temples, Kandyan history and the Esala Perahera festival.',
     'English,Sinhala,Tamil', 'CULTURAL,FOOD',
     'Kandy', 45.00, true, true, 4.8, 189,
     '+94777654321', 'priya.guide@gmail.com', NOW(), NOW()),
    ('Roshan Fernando',
     'Professional surf instructor and coastal guide. Certified lifeguard. Based in Arugam Bay for 8 years.',
     'English,Sinhala', 'SURFING,WILDLIFE',
     'Ampara', 55.00, true, true, 4.7, 156,
     '+94712345678', 'roshan.surf@gmail.com', NOW(), NOW()),
    ('Amali Jayasinghe',
     'Ayurveda wellness guide and herbal medicine expert. Conducts authentic village ayurveda experiences near Galle.',
     'English,Sinhala', 'AYURVEDA,CULTURAL',
     'Galle', 40.00, true, true, 4.8, 98,
     '+94723456789', 'amali.ayur@gmail.com', NOW(), NOW()),
    ('Nimal Wickrama',
     'Expert trekking guide for Ella Rock, Knuckles Range and Adam''s Peak. First aid certified. 15 years experience.',
     'English,Sinhala,German', 'TREKKING,PHOTOGRAPHY',
     'Badulla', 50.00, true, true, 4.9, 312,
     '+94734567890', 'nimal.trek@gmail.com', NOW(), NOW()),
    ('Saman Rajapaksa',
     'Bird watching specialist with knowledge of over 400 Sri Lankan bird species. Regular guide at Sinharaja and Kitulgala.',
     'English,Sinhala', 'BIRDWATCHING,WILDLIFE',
     'Ratnapura', 55.00, true, true, 4.7, 87,
     '+94745678901', 'saman.birds@gmail.com', NOW(), NOW()),
    ('Dilini Cooray',
     'Food and cooking guide based in Colombo. Conducts Sri Lankan cooking classes and authentic street food tours.',
     'English,Sinhala,Tamil,French', 'FOOD,CULTURAL',
     'Colombo', 35.00, true, true, 4.6, 143,
     '+94756789012', 'dilini.food@gmail.com', NOW(), NOW()),
    ('Asanka Mendis',
     'Photography guide specialising in golden hour shoots at Sri Lanka top scenic spots. Professional photographer.',
     'English,Sinhala,Japanese', 'PHOTOGRAPHY,TREKKING',
     'Nuwara Eliya', 60.00, true, true, 4.8, 76,
     '+94767890123', 'asanka.photo@gmail.com', NOW(), NOW())
) AS new_data (full_name, bio, languages, specialties,
    district, price_per_day, verified, available,
    rating, review_count, phone, email,
    created_at, updated_at)
WHERE NOT EXISTS (SELECT 1 FROM tour_guides LIMIT 1);


INSERT INTO destinations (name, district, province, description,
    short_description, category, best_months, activities,
    latitude, longitude, cover_image_url, travel_time_from,
    entry_fee, opening_hours, featured, active,
    rating, review_count, unesco_status, created_at, updated_at)
SELECT * FROM (VALUES
    ('Sigiriya', 'Matale', 'Central Province',
     'Sigiriya or Lion Rock is an ancient rock fortress and palace ruin situated in the central Matale District. A UNESCO World Heritage Site rising 200 metres above the surrounding plains.',
     'Ancient rock fortress and UNESCO World Heritage Site rising 200m above the plains.',
     'HERITAGE', 'January,February,March,April,July,August,September',
     'hiking,history,photography,archaeology',
     7.9570, 80.7603, NULL,
     'Colombo:4h by road,Kandy:2h by road,Dambulla:20min by road',
     'USD 30 (foreigners), LKR 100 (locals)', '7:00 AM - 5:30 PM daily',
     true, true, 4.8, 1250, 'UNESCO World Heritage Site', NOW(), NOW()),
    ('Ella', 'Badulla', 'Uva Province',
     'Ella is a small town in the Badulla District surrounded by mountains and tea plantations. Famous for the Nine Arch Bridge, Ella Rock hike, and the scenic train journey from Kandy.',
     'Mountain town famous for scenic train rides, tea plantations and epic hikes.',
     'HILL', 'January,February,March,April,August,September',
     'hiking,photography,tea-tours,train-rides',
     6.8667, 81.0466, NULL,
     'Colombo:6h by road,Kandy:3h by train (scenic),Yala:3h by road',
     'Free (Ella Rock hike LKR 200)', 'Open all day',
     true, true, 4.7, 987, NULL, NOW(), NOW()),
    ('Kandy', 'Kandy', 'Central Province',
     'Kandy is the cultural capital of Sri Lanka and home to the famous Temple of the Tooth Relic. A UNESCO World Heritage Site. The annual Esala Perahera festival in August is one of the grandest processions in Asia.',
     'Cultural capital of Sri Lanka with the sacred Temple of the Tooth Relic.',
     'CULTURAL', 'January,February,March,July,August,December',
     'temples,cultural-shows,botanical-gardens,trekking',
     7.2906, 80.6337, NULL,
     'Colombo:3h by road or train,Sigiriya:2h by road,Ella:3h by train',
     'Temple: USD 15 (foreigners)', 'Open all day — Temple 5:30AM-8PM',
     true, true, 4.6, 1456, 'UNESCO World Heritage Site', NOW(), NOW()),
    ('Yala National Park', 'Hambantota', 'Southern Province',
     'Yala National Park is the most visited and second largest national park in Sri Lanka. It has the highest density of leopards in the world.',
     'World famous wildlife park with the highest leopard density on earth.',
     'WILDLIFE', 'February,March,April,May,June,July,August,September',
     'safari,wildlife,photography,birdwatching',
     6.3728, 81.5216, NULL,
     'Colombo:5h by road,Galle:3h by road,Ella:3h by road',
     'USD 25 per person + USD 15 vehicle (foreigners)', '6:00 AM - 6:00 PM (Block 1)',
     true, true, 4.9, 2341, NULL, NOW(), NOW()),
    ('Galle Fort', 'Galle', 'Southern Province',
     'Galle Fort is a UNESCO World Heritage Site built first in 1588 by the Portuguese and then extensively fortified by the Dutch during the 17th century.',
     'Historic Dutch colonial fort and UNESCO World Heritage Site on the southern coast.',
     'HERITAGE', 'November,December,January,February,March,April',
     'history,architecture,shopping,cafes,photography',
     6.0269, 80.2167, NULL,
     'Colombo:2h by road or train,Mirissa:30min by road',
     'Free to enter the fort', 'Open 24 hours',
     true, true, 4.7, 1876, 'UNESCO World Heritage Site', NOW(), NOW()),
    ('Mirissa', 'Matara', 'Southern Province',
     'Mirissa is a small town on the south coast of Sri Lanka known for its beautiful crescent-shaped beach and world-class whale watching.',
     'Beautiful crescent beach and the best whale watching destination in Sri Lanka.',
     'BEACH', 'November,December,January,February,March,April',
     'whale-watching,swimming,snorkeling,surfing,beach',
     5.9483, 80.4716, NULL,
     'Colombo:3h by road,Galle:30min by road',
     'Beach free. Whale watching USD 30-40', 'Open all day',
     true, true, 4.6, 1123, NULL, NOW(), NOW()),
    ('Arugam Bay', 'Ampara', 'Eastern Province',
     'Arugam Bay is internationally renowned as one of the top surfing destinations in the world. The Main Point surf break is famous among professional surfers.',
     'World-class surf destination on the east coast — international surfers paradise.',
     'SURF', 'May,June,July,August,September,October',
     'surfing,swimming,beach,elephant-safari',
     6.8403, 81.8362, NULL,
     'Colombo:8h by road,Ella:3h by road',
     'Beach free. Surf lessons USD 20-30', 'Open all day',
     true, true, 4.7, 876, NULL, NOW(), NOW()),
    ('Nuwara Eliya', 'Nuwara Eliya', 'Central Province',
     'Nuwara Eliya is a city in the tea country of central Sri Lanka nicknamed Little England due to its British colonial architecture.',
     'Hill station nicknamed Little England surrounded by tea estates and cool misty air.',
     'HILL', 'January,February,March,April',
     'tea-tours,hiking,horton-plains,photography,golf',
     6.9497, 80.7891, NULL,
     'Colombo:4h by road,Kandy:2.5h by road,Ella:2h by road',
     'Horton Plains: USD 25 (foreigners)', 'Open all day — Horton Plains 6AM-6PM',
     true, true, 4.5, 765, NULL, NOW(), NOW()),
    ('Trincomalee', 'Trincomalee', 'Eastern Province',
     'Trincomalee is a port city on the northeast coast known for one of the finest natural harbours in the world. Nilaveli and Uppuveli beaches offer crystal clear water.',
     'Pristine east coast beaches with world-class snorkeling at Pigeon Island.',
     'BEACH', 'April,May,June,July,August,September',
     'snorkeling,diving,swimming,whale-watching,temples',
     8.5874, 81.2152, NULL,
     'Colombo:6h by road,Sigiriya:3h by road',
     'Pigeon Island: USD 15 (foreigners)', 'Open all day',
     false, true, 4.6, 543, NULL, NOW(), NOW()),
    ('Anuradhapura', 'Anuradhapura', 'North Central Province',
     'Anuradhapura is one of the ancient capitals of Sri Lanka and is a UNESCO World Heritage Site. Contains the Sri Maha Bodhi tree — the oldest human-planted tree in the world.',
     'Ancient sacred city with 2500 year old bodhi tree and massive dagobas.',
     'CULTURAL', 'January,February,March,April,May,June,July,August',
     'history,temples,cycling,archaeology,pilgrimage',
     8.3114, 80.4037, NULL,
     'Colombo:4h by road,Sigiriya:1.5h by road',
     'USD 25 (foreigners)', '6:00 AM - 6:00 PM',
     false, true, 4.5, 654, 'UNESCO World Heritage Site', NOW(), NOW()),
    ('Polonnaruwa', 'Polonnaruwa', 'North Central Province',
     'Polonnaruwa is the second most ancient of Sri Lanka kingdoms. A UNESCO World Heritage Site with the Gal Vihara rock temple with magnificent Buddha statues carved from a single granite face.',
     'Ancient kingdom ruins with magnificent rock-carved Buddha statues.',
     'HERITAGE', 'January,February,March,April,May,June',
     'history,cycling,archaeology,photography',
     7.9403, 81.0188, NULL,
     'Colombo:5h by road,Sigiriya:1h by road',
     'USD 25 (foreigners)', '7:00 AM - 6:00 PM',
     false, true, 4.6, 432, 'UNESCO World Heritage Site', NOW(), NOW()),
    ('Jaffna', 'Jaffna', 'Northern Province',
     'Jaffna is the largest city in northern Sri Lanka with a distinct Tamil culture. Known for its unique cuisine, colorful Hindu temples and the historic Jaffna Fort.',
     'Culturally unique northern city with Tamil heritage, temples and island excursions.',
     'CULTURAL', 'May,June,July,August,September',
     'temples,history,island-tours,food,cycling',
     9.6615, 80.0255, NULL,
     'Colombo:8h by road or 1h by plane',
     'Fort: Free. Temples: nominal fee', 'Open all day',
     false, true, 4.4, 321, NULL, NOW(), NOW())
) AS new_data (name, district, province, description,
    short_description, category, best_months, activities,
    latitude, longitude, cover_image_url, travel_time_from,
    entry_fee, opening_hours, featured, active,
    rating, review_count, unesco_status, created_at, updated_at)
WHERE NOT EXISTS (SELECT 1 FROM destinations LIMIT 1);


-- Extra AI planning sample data for Colombo, Kalutara, Galle, Matara,
-- Kegalle, Nuwara Eliya, Kandy and Ratnapura.
-- These rows insert independently, so they can enrich an existing database.

INSERT INTO destinations (name, district, province, description,
    short_description, category, best_months, activities,
    latitude, longitude, cover_image_url, travel_time_from,
    entry_fee, opening_hours, featured, active,
    rating, review_count, unesco_status, created_at, updated_at)
SELECT * FROM (VALUES
    ('Colombo Fort and Pettah Heritage Walk', 'Colombo', 'Western Province',
     'A compact city route through Colombo Fort, Dutch Hospital, red-brick colonial buildings, Pettah market lanes, Jami Ul-Alfar Mosque exterior and local snack stops. Good first-day orientation for travelers arriving in Sri Lanka.',
     'City heritage walk linking Fort, Pettah markets, colonial streets and local food stops.',
     'CITY', 'January,February,March,April,July,August,December',
     'city-walk,history,food,markets,photography',
     6.9344, 79.8428, NULL,
     'Airport:45min by road,Mount Lavinia:35min by road,Galle Face:10min by road',
     'Free except museum or snack costs', 'Best 7:30 AM - 11:00 AM or 4:00 PM - 7:00 PM',
     true, true, 4.5, 610, NULL, NOW(), NOW()),
    ('Mount Lavinia Beach Sunset', 'Colombo', 'Western Province',
     'A relaxed coastal stop south of Colombo with sunset views, seafood restaurants, colonial hotel history and an easy beach walk. Works well as a soft landing day after a flight.',
     'Easy Colombo beach sunset stop with seafood, coastal views and relaxed evening atmosphere.',
     'BEACH', 'January,February,March,April,December',
     'beach,food,sunset,relaxation,photography',
     6.8390, 79.8639, NULL,
     'Colombo Fort:35min by road or train,Airport:1h by road',
     'Beach free', 'Open all day',
     true, true, 4.4, 480, NULL, NOW(), NOW()),
    ('Kalutara Bodhiya and Richmond Castle', 'Kalutara', 'Western Province',
     'A cultural half-day combining the sacred Kalutara Bodhiya, riverside views and Richmond Castle, a mansion blending Sri Lankan, Indian and British architecture.',
     'Sacred temple, river views and colonial mansion visit in one easy Kalutara route.',
     'CULTURAL', 'January,February,March,April,December',
     'temples,architecture,history,river-views,photography',
     6.5854, 79.9607, NULL,
     'Colombo:1h 30min by road,Galle:1h 45min by road',
     'Temple free. Richmond Castle small local entry fee', '8:00 AM - 5:00 PM',
     false, true, 4.4, 320, NULL, NOW(), NOW()),
    ('Bentota and Beruwala Coast', 'Kalutara', 'Western Province',
     'A beach and lagoon corridor ideal for slow coastal travel, river safaris, water sports and relaxed seafood meals. Useful stop between Colombo and Galle.',
     'Beach, lagoon, water sports and river safari stop between Colombo and Galle.',
     'BEACH', 'November,December,January,February,March,April',
     'beach,boat-safari,water-sports,food,relaxation',
     6.4210, 79.9950, NULL,
     'Colombo:1h 45min by road,Galle:1h 15min by road',
     'Beach free. Boat safari extra', 'Open all day',
     true, true, 4.6, 710, NULL, NOW(), NOW()),
    ('Galle Fort Slow Day', 'Galle', 'Southern Province',
     'A full day inside the UNESCO-listed Galle Fort with rampart walks, Dutch-era lanes, museums, cafes, lighthouse views, boutiques and sunset from the sea wall.',
     'UNESCO fort day with rampart walks, cafes, colonial streets and lighthouse views.',
     'HERITAGE', 'November,December,January,February,March,April',
     'history,architecture,cafes,shopping,sunset,photography',
     6.0269, 80.2167, NULL,
     'Colombo:2h by expressway,Matara:1h by road,Mirissa:45min by road',
     'Fort free. Museums optional', 'Open 24 hours',
     true, true, 4.8, 2100, 'UNESCO World Heritage Site', NOW(), NOW()),
    ('Hikkaduwa Coral and Beach', 'Galle', 'Southern Province',
     'A lively beach town with coral gardens, snorkeling boats, surf breaks and turtle sightings. Good for travelers wanting beach energy near Galle.',
     'Snorkeling, surf, coral gardens and beach cafes on the Galle coast.',
     'BEACH', 'November,December,January,February,March,April',
     'snorkeling,surfing,beach,seafood,photography',
     6.1395, 80.1063, NULL,
     'Galle:25min by road,Colombo:2h by road',
     'Beach free. Snorkeling boat extra', 'Open all day',
     false, true, 4.5, 890, NULL, NOW(), NOW()),
    ('Mirissa Whale Watching and Coconut Tree Hill', 'Matara', 'Southern Province',
     'A southern coast highlight combining early morning whale watching, relaxed Mirissa beach time and sunset photos from Coconut Tree Hill.',
     'Whale watching, beach time and Coconut Tree Hill sunset in Mirissa.',
     'BEACH', 'November,December,January,February,March,April',
     'whale-watching,beach,sunset,photography,seafood',
     5.9483, 80.4716, NULL,
     'Galle:45min by road,Matara:25min by road,Colombo:3h by road',
     'Beach free. Whale watching USD 35-50', 'Whale boats usually 6:00 AM - 7:00 AM',
     true, true, 4.7, 1450, NULL, NOW(), NOW()),
    ('Weligama Surf and Ahangama Cafes', 'Matara', 'Southern Province',
     'A beginner-friendly surf coast with board rentals, surf schools, seafood shacks and a growing cafe scene between Weligama and Ahangama.',
     'Beginner surf, beach cafes and relaxed south-coast energy.',
     'SURF', 'November,December,January,February,March,April',
     'surfing,beach,cafes,food,relaxation',
     5.9730, 80.4297, NULL,
     'Galle:35min by road,Mirissa:20min by road,Matara:30min by road',
     'Beach free. Surf lesson USD 15-30', 'Best surf mornings and late afternoons',
     false, true, 4.6, 780, NULL, NOW(), NOW()),
    ('Pinnawala Elephant Orphanage and River View', 'Kegalle', 'Sabaragamuwa Province',
     'A popular Kegalle stop known for elephants and riverside viewing. Best used as a short stop between Colombo and Kandy, with ethical expectations explained clearly to travelers.',
     'Elephant and riverside stop on the Colombo to Kandy road.',
     'WILDLIFE', 'January,February,March,April,July,August,December',
     'wildlife,river-views,photography,family',
     7.3008, 80.3889, NULL,
     'Colombo:2h 30min by road,Kandy:1h 30min by road',
     'Ticketed attraction', '8:30 AM - 5:30 PM',
     false, true, 4.2, 970, NULL, NOW(), NOW()),
    ('Kitulgala Adventure and Kelani River', 'Kegalle', 'Sabaragamuwa Province',
     'Sri Lanka adventure hub for white-water rafting, rainforest walks, canyoning and birding along the Kelani River. Ideal for active travelers between Colombo and hill country.',
     'Rafting, rainforest walks and river adventure between Colombo and Kandy.',
     'ADVENTURE', 'January,February,March,April,August,September,December',
     'rafting,trekking,birdwatching,canyoning,adventure',
     6.9894, 80.4197, NULL,
     'Colombo:2h 45min by road,Kandy:2h 30min by road,Nuwara Eliya:2h 30min by road',
     'Rafting packages vary by operator', 'Best 8:00 AM - 4:00 PM',
     true, true, 4.8, 640, NULL, NOW(), NOW()),
    ('Nuwara Eliya Tea Country and Gregory Lake', 'Nuwara Eliya', 'Central Province',
     'A cool-climate hill-country day with tea estate visits, colonial streets, Gregory Lake, strawberry stops and misty viewpoints.',
     'Tea estates, cool climate, colonial streets and Gregory Lake in Little England.',
     'HILL', 'January,February,March,April,December',
     'tea-tours,lake,photography,walking,relaxation',
     6.9497, 80.7891, NULL,
     'Kandy:2h 30min by road,Ella:2h 15min by road,Colombo:5h by road',
     'Lake activities extra. Tea factory tours may charge small fee', 'Open all day',
     true, true, 4.6, 1250, NULL, NOW(), NOW()),
    ('Horton Plains and Worlds End', 'Nuwara Eliya', 'Central Province',
     'A highland national park walk through cloud forest and grassland to Worlds End viewpoint and Bakers Falls. Best started before sunrise for clear views.',
     'Cloud forest hike to Worlds End viewpoint and Bakers Falls.',
     'HILL', 'January,February,March,April,July,August,December',
     'hiking,wildlife,photography,nature,birdwatching',
     6.8021, 80.8070, NULL,
     'Nuwara Eliya:1h by road,Ella:2h 30min by road',
     'Ticketed national park entry', '6:00 AM - 6:00 PM',
     true, true, 4.8, 980, NULL, NOW(), NOW()),
    ('Temple of the Tooth and Kandy Lake', 'Kandy', 'Central Province',
     'A sacred cultural route around Sri Dalada Maligawa, Kandy Lake, old city streets and evening cultural performance. Strong choice for first-time visitors.',
     'Sacred temple, lake walk and Kandyan culture in the hill capital.',
     'RELIGIOUS', 'January,February,March,July,August,December',
     'temples,culture,history,lake-walk,photography',
     7.2936, 80.6413, NULL,
     'Colombo:3h by road or train,Nuwara Eliya:2h 30min by road,Sigiriya:2h 30min by road',
     'Temple foreigner ticket applies', 'Temple 5:30 AM - 8:00 PM',
     true, true, 4.8, 2200, 'UNESCO World Heritage Site', NOW(), NOW()),
    ('Peradeniya Botanical Gardens', 'Kandy', 'Central Province',
     'A grand botanical garden near Kandy with royal palms, orchids, giant bamboo, open lawns and riverside walking paths. Excellent slow half-day for families and couples.',
     'Royal botanical gardens with orchids, palm avenues and riverside walks.',
     'HILL', 'January,February,March,April,July,August,December',
     'gardens,walking,photography,family,relaxation',
     7.2717, 80.5953, NULL,
     'Kandy:25min by road,Colombo:3h by road',
     'Ticketed garden entry', '7:30 AM - 5:30 PM',
     false, true, 4.7, 1300, NULL, NOW(), NOW()),
    ('Ratnapura Gem City and Market', 'Ratnapura', 'Sabaragamuwa Province',
     'Sri Lanka gem capital with gem museums, traditional mining stories, local markets and routes toward Sinharaja and Adam''s Peak. Best for culture, crafts and local trade insight.',
     'Gem museums, markets and mining heritage in Sri Lanka sapphire capital.',
     'CULTURAL', 'January,February,March,April,December',
     'gems,markets,culture,history,photography',
     6.6828, 80.3992, NULL,
     'Colombo:2h 45min by road,Nuwara Eliya:3h by road,Kitulgala:1h 45min by road',
     'Museum ticket may apply', 'Best 9:00 AM - 4:00 PM',
     false, true, 4.5, 540, NULL, NOW(), NOW()),
    ('Sinharaja Rainforest Edge', 'Ratnapura', 'Sabaragamuwa Province',
     'A biodiversity-rich rainforest experience from the Ratnapura side of Sinharaja, suitable for birding, nature walks, endemic species and slow eco-travel.',
     'Rainforest walks, endemic birds and eco-travel from the Ratnapura side.',
     'WILDLIFE', 'January,February,March,April,August,September,December',
     'rainforest,birdwatching,walking,wildlife,photography',
     6.4088, 80.4820, NULL,
     'Ratnapura:2h by road,Galle:2h 30min by road,Colombo:4h by road',
     'Forest entry and guide fee apply', '6:30 AM - 5:00 PM',
     true, true, 4.9, 720, 'UNESCO World Heritage Site', NOW(), NOW())
) AS new_data (name, district, province, description,
    short_description, category, best_months, activities,
    latitude, longitude, cover_image_url, travel_time_from,
    entry_fee, opening_hours, featured, active,
    rating, review_count, unesco_status, created_at, updated_at)
WHERE NOT EXISTS (
    SELECT 1 FROM destinations d WHERE LOWER(d.name) = LOWER(new_data.name)
);

INSERT INTO hidden_gems (title, description, category, district,
    latitude, longitude, how_to_get_there, best_time, tips,
    approved, rating, review_count, created_at, updated_at)
SELECT * FROM (VALUES
    ('Diyatha Uyana Evening Walk',
     'A calm lakeside market and walking area near Battaramulla with food kiosks, sunset reflections and local weekend atmosphere.',
     'VILLAGE', 'Colombo', 6.9048, 79.9088,
     'Take a taxi or tuk-tuk from Colombo city toward Battaramulla. Best combined with Parliament lake area.',
     'Evenings year round', 'Good low-effort first evening after arrival. Carry cash for snacks.',
     true, 4.4, 210, NOW(), NOW()),
    ('Seema Malaka Quiet Temple Stop',
     'A peaceful temple pavilion on Beira Lake designed by Geoffrey Bawa, useful as a short reflective stop in busy Colombo.',
     'TEMPLE', 'Colombo', 6.9169, 79.8545,
     'Walk or taxi from Gangaramaya Temple. It is beside Beira Lake in central Colombo.',
     'Early morning or late afternoon', 'Dress modestly. Combine with Gangaramaya and Galle Face.',
     true, 4.5, 185, NOW(), NOW()),
    ('Fa Hien Cave',
     'A major prehistoric cave site near Bulathsinhala connected with early human habitation in Sri Lanka, surrounded by forested limestone scenery.',
     'RUINS', 'Kalutara', 6.6442, 80.1758,
     'From Kalutara or Horana travel to Bulathsinhala, then continue by local road to the cave temple area.',
     'January to April and December', 'Wear shoes with grip. Steps can be slippery after rain.',
     true, 4.6, 120, NOW(), NOW()),
    ('Thudugala Ella',
     'A small waterfall and natural pool hidden in rubber estate country near Dodangoda, good for a short nature break from the coastal road.',
     'WATERFALL', 'Kalutara', 6.5625, 80.0602,
     'From Kalutara take the Dodangoda road and ask locals for Thudugala Falls. Short walk from the village road.',
     'December to April', 'Avoid after heavy rain. Go with locals if unfamiliar with the path.',
     true, 4.5, 160, NOW(), NOW()),
    ('Japanese Peace Pagoda Rumassala',
     'A white hilltop pagoda above Unawatuna with ocean views, forest paths and a quieter spiritual atmosphere near Galle.',
     'TEMPLE', 'Galle', 6.0186, 80.2402,
     'Take a tuk-tuk from Galle Fort or Unawatuna to Rumassala, then walk the final path.',
     'November to April', 'Best near sunset. Dress respectfully and keep voices low.',
     true, 4.7, 390, NOW(), NOW()),
    ('Kanneliya Rainforest Edge',
     'A lush rainforest reserve north of Galle with streams, endemic plants, waterfalls and guided nature trails.',
     'VIEWPOINT', 'Galle', 6.2511, 80.3372,
     'Drive from Galle via Udugama. Hire an official guide at the forest entrance.',
     'January to April and August', 'Leech socks are useful. Start early and carry water.',
     true, 4.8, 240, NOW(), NOW()),
    ('Dondra Head Lighthouse',
     'Sri Lanka southernmost lighthouse with strong ocean views, palm-lined roads and quiet coastal photography spots.',
     'VIEWPOINT', 'Matara', 5.9218, 80.5940,
     'From Matara town take a tuk-tuk or bus toward Dondra. The lighthouse is near the point.',
     'November to April', 'Ask permission before entering lighthouse grounds. Best light is morning.',
     true, 4.6, 260, NOW(), NOW()),
    ('Madiha Turtle Coast',
     'A quieter reef and beach area near Matara where turtles are often seen from the shore, with small cafes and calm swimming pockets.',
     'BEACH', 'Matara', 5.9368, 80.5156,
     'Take a tuk-tuk from Matara or Mirissa toward Madiha. Walk along the reef-side beach.',
     'November to April', 'Do not touch turtles or stand on reef. Bring reef-safe sunscreen.',
     true, 4.7, 310, NOW(), NOW()),
    ('Belilena Cave Kitulgala',
     'A cave near Kitulgala linked to prehistoric Balangoda Man discoveries, reached through forest and village paths.',
     'RUINS', 'Kegalle', 7.0021, 80.4315,
     'From Kitulgala town hire a local guide or tuk-tuk to the trailhead, then walk uphill through forest.',
     'January to April and August', 'Trail is muddy after rain. Combine with rafting for an adventure day.',
     true, 4.6, 130, NOW(), NOW()),
    ('Bopath Ella Stopover',
     'A photogenic waterfall shaped like a Bo leaf, commonly visited by locals but still useful as a refreshing route break near Ratnapura and Kegalle routes.',
     'WATERFALL', 'Kegalle', 6.8017, 80.3689,
     'Reach via Kuruwita from Ratnapura or through Avissawella routes. Short walk from parking area.',
     'December to April', 'Can be crowded on weekends. Avoid swimming in strong flow.',
     true, 4.5, 330, NOW(), NOW()),
    ('Lovers Leap Waterfall Nuwara Eliya',
     'A scenic waterfall above tea estates near Nuwara Eliya, reached by a short uphill walk with views over the town.',
     'WATERFALL', 'Nuwara Eliya', 6.9675, 80.7913,
     'Start near Pedro Tea Estate and follow the uphill path. Tuk-tuk from town takes about 15 minutes.',
     'January to April', 'Morning is clearest. Wear shoes suitable for wet paths.',
     true, 4.7, 280, NOW(), NOW()),
    ('Moon Plains Viewpoint',
     'A highland viewpoint near Nuwara Eliya with open grasslands, wind, mist and 360-degree mountain views on clear mornings.',
     'VIEWPOINT', 'Nuwara Eliya', 6.9283, 80.8289,
     'Drive or tuk-tuk from Nuwara Eliya town to the Moon Plains entrance.',
     'January to April and December', 'Go early before cloud cover. Take a jacket.',
     true, 4.6, 245, NOW(), NOW()),
    ('Degaldoruwa Cave Temple',
     'A lesser-visited cave temple near Kandy with Kandyan-era murals, quiet courtyards and strong cultural value.',
     'TEMPLE', 'Kandy', 7.3129, 80.6932,
     'Take a tuk-tuk from Kandy toward Amunugama. Ask for Degaldoruwa Raja Maha Viharaya.',
     'Year round', 'Visit with a respectful dress code. A local caretaker may explain murals.',
     true, 4.6, 150, NOW(), NOW()),
    ('Hanthana Tea and View Trail',
     'A scenic tea-country ridge near Kandy with city views, cool air and short hiking possibilities without traveling far.',
     'VIEWPOINT', 'Kandy', 7.2547, 80.6122,
     'Take a tuk-tuk from Kandy toward Hanthana. Start from tea estate roads or the Ceylon Tea Museum area.',
     'January to April and July to September', 'Best early morning. Mist can arrive quickly.',
     true, 4.7, 290, NOW(), NOW()),
    ('Gem Mine Village Visit Elapatha',
     'A traditional gem mining village area near Ratnapura where travelers can understand sapphire mining culture and local livelihoods.',
     'VILLAGE', 'Ratnapura', 6.6489, 80.3695,
     'From Ratnapura town hire a local tuk-tuk toward Elapatha and arrange a visit through a known local contact.',
     'January to April and December', 'Do not enter pits without permission. Agree price before visiting.',
     true, 4.5, 115, NOW(), NOW()),
    ('Katugas Ella',
     'A forest-fringed waterfall close to Ratnapura town, useful for a short nature break after gem market visits.',
     'WATERFALL', 'Ratnapura', 6.7154, 80.3851,
     'Take a tuk-tuk from Ratnapura town toward the Katugas Ella access path.',
     'December to April', 'Path can be slippery. Avoid swimming during rain.',
     true, 4.4, 170, NOW(), NOW())
) AS new_data (title, description, category, district,
    latitude, longitude, how_to_get_there, best_time, tips,
    approved, rating, review_count, created_at, updated_at)
WHERE NOT EXISTS (
    SELECT 1 FROM hidden_gems g WHERE LOWER(g.title) = LOWER(new_data.title)
);

INSERT INTO events (title, description, category, region, location,
    start_date, end_date, is_recurring, created_at)
SELECT * FROM (VALUES
    ('Colombo Street Food Weekend',
     'A food-focused weekend around Galle Face, Pettah snacks, kottu, isso wade, hoppers and modern Sri Lankan cafes. Useful for city arrival itineraries.',
     'FOOD', 'Colombo', 'Colombo Fort and Galle Face',
     '2026-08-21'::date, '2026-08-23'::date, true, NOW()),
    ('Kalutara Coastal Temple Season',
     'A local cultural period highlighting Kalutara Bodhiya visits, riverside evening walks and coastal temple stops between Colombo and Bentota.',
     'RELIGIOUS', 'Kalutara', 'Kalutara Bodhiya',
     '2026-12-04'::date, '2026-12-06'::date, true, NOW()),
    ('Galle Fort Art and Heritage Days',
     'A heritage weekend inside Galle Fort with art walks, fort architecture tours, cafe events and sunset rampart gatherings.',
     'ENTERTAINMENT', 'Galle', 'Galle Fort',
     '2026-11-20'::date, '2026-11-22'::date, true, NOW()),
    ('Matara Southern Coast Surf Week',
     'A south coast surf and beach week around Weligama, Madiha, Mirissa and Ahangama with beginner lessons and sunset gatherings.',
     'SURF', 'Matara', 'Weligama and Mirissa',
     '2026-12-10'::date, '2026-12-17'::date, true, NOW()),
    ('Kitulgala River Adventure Season',
     'A practical adventure window for rafting, rainforest walks and canyoning around Kitulgala when river conditions are usually suitable.',
     'ENTERTAINMENT', 'Kegalle', 'Kitulgala',
     '2026-08-01'::date, '2026-09-15'::date, true, NOW()),
    ('Nuwara Eliya Tea and Garden Weekend',
     'A cool-climate weekend for tea estate visits, Gregory Lake walks, garden stops and misty hill-country photography.',
     'ENTERTAINMENT', 'Nuwara Eliya', 'Nuwara Eliya Town',
     '2026-12-18'::date, '2026-12-20'::date, true, NOW()),
    ('Kandy Esala Cultural Nights',
     'Cultural evenings around the Kandy Esala season with temple visits, dance shows, drumming and lake-side night walks.',
     'FESTIVAL', 'Kandy', 'Kandy City',
     '2026-08-03'::date, '2026-08-13'::date, true, NOW()),
    ('Ratnapura Gem and Rainforest Week',
     'A local culture and nature week connecting gem-market visits, traditional mining stories and rainforest-edge day trips.',
     'ENTERTAINMENT', 'Ratnapura', 'Ratnapura Town',
     '2026-12-07'::date, '2026-12-13'::date, true, NOW())
) AS new_data (title, description, category, region, location,
    start_date, end_date, is_recurring, created_at)
WHERE NOT EXISTS (
    SELECT 1 FROM events e WHERE LOWER(e.title) = LOWER(new_data.title)
);

UPDATE events SET latitude = 6.9271, longitude = 79.8449
WHERE title IN ('Colombo Food Festival', 'Colombo Street Food Weekend')
  AND latitude IS NULL;

UPDATE events SET latitude = 6.5854, longitude = 79.9607
WHERE title = 'Kalutara Coastal Temple Season'
  AND latitude IS NULL;

UPDATE events SET latitude = 6.0269, longitude = 80.2167
WHERE title IN ('Galle Literary Festival', 'Christmas in Galle Fort',
                'Galle Fort Art and Heritage Days')
  AND latitude IS NULL;

UPDATE events SET latitude = 6.1395, longitude = 80.1063
WHERE title = 'Hikkaduwa Coral Festival'
  AND latitude IS NULL;

UPDATE events SET latitude = 5.9483, longitude = 80.4716
WHERE title IN ('Whale Watching Season â€” Mirissa',
                'Matara Southern Coast Surf Week')
  AND latitude IS NULL;

UPDATE events SET latitude = 6.9894, longitude = 80.4197
WHERE title = 'Kitulgala River Adventure Season'
  AND latitude IS NULL;

UPDATE events SET latitude = 6.9497, longitude = 80.7891
WHERE title = 'Nuwara Eliya Tea and Garden Weekend'
  AND latitude IS NULL;

UPDATE events SET latitude = 7.2936, longitude = 80.6413
WHERE title IN ('Esala Perahera', 'Kandy Esala Cultural Nights')
  AND latitude IS NULL;

UPDATE events SET latitude = 6.6828, longitude = 80.3992
WHERE title = 'Ratnapura Gem and Rainforest Week'
  AND latitude IS NULL;

INSERT INTO users (name, email, password, role, nationality, created_at, updated_at)
SELECT * FROM (VALUES
    ('Admin User',
     'admin@exploreceylon.com',
     '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.',
     'ADMIN',
     'Sri Lankan',
     NOW(), NOW()),
    ('Kamal Perera',
     'nimal@gmail.com',
     '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.',
     'TRAVELER',
     'Sri Lankan',
     NOW(), NOW()),
    ('supun Perera',
     'supun@gmail.com',
     '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.',
     'TRAVELER',
     'Sri Lankan',
     NOW(), NOW()),
    ('sadun Perera',
     'sadun@gmail.com',
     '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.',
     'TRAVELER',
     'India',
     NOW(), NOW())
) AS new_data (name, email, password, role, nationality, created_at, updated_at)
WHERE NOT EXISTS (SELECT 1 FROM users LIMIT 1);

-- ─────────────────────────────────────────────────────────────
-- Booking status migration: old 6-state enum → new 4-state enum.
-- Idempotent — runs on every startup (spring.sql.init.mode=always),
-- affects 0 rows once all bookings use the new names.
--   PENDING      → PENDING_PAYMENT
--   ADVANCE_PAID → CONFIRMED   (20% advance paid)
--   FULLY_PAID   → COMPLETED   (80% balance paid)
--   CONFIRMED / COMPLETED / CANCELLED unchanged
-- ─────────────────────────────────────────────────────────────
UPDATE guide_bookings   SET status = 'PENDING_PAYMENT' WHERE status = 'PENDING';
UPDATE guide_bookings   SET status = 'CONFIRMED'       WHERE status = 'ADVANCE_PAID';
UPDATE guide_bookings   SET status = 'COMPLETED'       WHERE status = 'FULLY_PAID';
UPDATE vehicle_bookings SET status = 'PENDING_PAYMENT' WHERE status = 'PENDING';
UPDATE vehicle_bookings SET status = 'CONFIRMED'       WHERE status = 'ADVANCE_PAID';
UPDATE vehicle_bookings SET status = 'COMPLETED'       WHERE status = 'FULLY_PAID';

-- ─────────────────────────────────────────────────────────────
-- Location gazetteer seed (fix 1): place-name → coordinates lookup
-- for trip-planning "from"/"to" geocoding, separate from the
-- destinations table. Idempotent — ON CONFLICT (name) DO NOTHING.
-- Mirrored in src/main/resources/data/locations_seed.sql for review.
-- ─────────────────────────────────────────────────────────────
INSERT INTO locations (name, latitude, longitude) VALUES
    ('Colombo',       6.9271, 79.8612),
    ('Kandy',         7.2906, 80.6337),
    ('Galle',         6.0535, 80.2210),
    ('Ella',          6.8667, 81.0466),
    ('Mirissa',       5.9483, 80.4589),
    ('Nuwara Eliya',  6.9497, 80.7891),
    ('Jaffna',        9.6615, 80.0255),
    ('Trincomalee',   8.5874, 81.2152),
    ('Batticaloa',    7.7102, 81.6924),
    ('Anuradhapura',  8.3114, 80.4037),
    ('Polonnaruwa',   7.9403, 81.0188),
    ('Sigiriya',      7.9570, 80.7603),
    ('Dambulla',      7.8675, 80.6517),
    ('Negombo',       7.2083, 79.8358),
    ('Bentota',       6.4260, 79.9955),
    ('Hikkaduwa',     6.1408, 80.1018),
    ('Unawatuna',     6.0108, 80.2495),
    ('Tangalle',      6.0244, 80.7934),
    ('Arugam Bay',    6.8400, 81.8360),
    ('Yala',          6.3728, 81.5165),
    ('Udawalawe',     6.4675, 80.8974),
    ('Ratnapura',     6.6828, 80.4126),
    ('Kegalle',       7.2513, 80.3464),
    ('Kitulgala',     6.9908, 80.4197),
    ('Badulla',       6.9895, 81.0557),
    ('Haputale',      6.7676, 80.9564),
    ('Bandarawela',   6.8333, 80.9833),
    ('Matara',        5.9549, 80.5550),
    ('Kalutara',      6.5854, 79.9607),
    ('Beruwala',      6.4788, 79.9828)
ON CONFLICT (name) DO NOTHING;
