INSERT INTO vehicles (name, type, brand, model, year, seats, color,
    price_per_day, currency, district, pickup_location,
    driver_included, airport_transfer, available,
    driver_name, driver_phone, driver_languages,
    description, rating, review_count, category,
    created_at, updated_at)
SELECT * FROM (VALUES
    ('Colombo City Tuk-Tuk', 'TUKTUK', 'Bajaj', 'RE', 2022, 3, 'Yellow',
        15.00, 'USD', 'Colombo', 'Colombo Fort',
        true, false, true,
        'Kamal Silva', '+94771234567', 'English, Sinhala',
        'Reliable tuk-tuk service around Colombo city', 4.5, 120, 'LOCAL',
        NOW(), NOW()),
    ('Airport Transfer Van', 'VAN', 'Toyota', 'HiAce', 2021, 8, 'White',
        45.00, 'USD', 'Colombo', 'BIA Katunayake Airport',
        true, true, true,
        'Nimal Perera', '+94777654321', 'English, Sinhala, Tamil',
        'Comfortable airport transfer van with AC', 4.8, 85, 'STANDARD',
        NOW(), NOW()),
    ('Kandy Hill Country Car', 'CAR', 'Toyota', 'Prius', 2020, 4, 'Silver',
        35.00, 'USD', 'Kandy', 'Kandy City Center',
        true, false, true,
        'Sunil Fernando', '+94765432109', 'English, Sinhala',
        'Comfortable car for hill country exploration', 4.6, 67, 'STANDARD',
        NOW(), NOW()),
    ('Ella Adventure Jeep', 'SUV', 'Jeep', 'Wrangler', 2019, 5, 'Green',
        55.00, 'USD', 'Badulla', 'Ella Town',
        true, false, true,
        'Roshan Dias', '+94712345678', 'English',
        'Perfect for Ella Rock and Nine Arch Bridge tours', 4.9, 43, 'PREMIUM',
        NOW(), NOW()),
    ('Galle Southern Tuk-Tuk', 'TUKTUK', 'Bajaj', 'RE', 2023, 3, 'Blue',
        12.00, 'USD', 'Galle', 'Galle Fort',
        true, false, true,
        'Priya Cooray', '+94723456789', 'English, Sinhala',
        'Best tuk-tuk for Galle Fort and southern coast', 4.4, 98, 'LOCAL',
        NOW(), NOW()),
    ('Colombo Luxury SUV', 'SUV', 'Toyota', 'Land Cruiser', 2022, 6, 'Black',
        85.00, 'USD', 'Colombo', 'Colombo 03',
        true, false, true,
        'Asanka Mendis', '+94734567890', 'English, Sinhala',
        'Premium SUV for luxury travel around Sri Lanka', 4.7, 32, 'LUXURY',
        NOW(), NOW()),
    ('Mirissa Beach Scooter', 'SCOOTER', 'Honda', 'Wave', 2021, 2, 'Red',
        18.00, 'USD', 'Matara', 'Mirissa Beach',
        false, false, true,
        NULL, NULL, NULL,
        'Self-drive scooter perfect for coastal exploration', 4.3, 156, 'ECONOMY',
        NOW(), NOW()),
    ('Sigiriya Cultural Van', 'MINIVAN', 'Toyota', 'KDH', 2020, 10, 'White',
        60.00, 'USD', 'Matale', 'Sigiriya Rock',
        true, false, true,
        'Chaminda Rathnayake', '+94745678901', 'English, Sinhala, Japanese',
        'Perfect for cultural triangle tours', 4.8, 54, 'STANDARD',
        NOW(), NOW())
) AS new_data (name, type, brand, model, year, seats, color,
    price_per_day, currency, district, pickup_location,
    driver_included, airport_transfer, available,
    driver_name, driver_phone, driver_languages,
    description, rating, review_count, category,
    created_at, updated_at)
WHERE NOT EXISTS (SELECT 1 FROM vehicles LIMIT 1);


INSERT INTO events (title, description, category, region,
    start_date, end_date, image_url, is_recurring, created_at)
SELECT * FROM (VALUES
    ('Vesak Festival',
     'Sri Lanka largest Buddhist festival celebrating the birth, enlightenment and passing of Lord Buddha. Lanterns and pandols lit across the island.',
     'FESTIVAL', 'Island-wide', '2026-05-12'::date, '2026-05-13'::date, NULL, true, NOW()),
    ('Esala Perahera',
     'Grand procession of the Temple of the Tooth Relic in Kandy. Elephants, drummers, fire dancers in spectacular parade.',
     'FESTIVAL', 'Kandy', '2026-08-03'::date, '2026-08-13'::date, NULL, true, NOW()),
    ('Sinhala and Tamil New Year',
     'Traditional Sri Lankan New Year celebrated by both Sinhalese and Tamil communities with rituals, games and special foods.',
     'FESTIVAL', 'Island-wide', '2026-04-13'::date, '2026-04-14'::date, NULL, true, NOW()),
    ('Thai Pongal',
     'Tamil harvest festival giving thanks to the Sun God. Traditional Pongal dish cooked and celebrations with kolam drawings.',
     'RELIGIOUS', 'Jaffna', '2026-01-14'::date, '2026-01-15'::date, NULL, true, NOW()),
    ('Kataragama Festival',
     'Major religious festival at the Kataragama temple complex attended by Buddhist, Hindu, Muslim and indigenous Vedda devotees.',
     'RELIGIOUS', 'Kataragama', '2026-07-28'::date, '2026-08-06'::date, NULL, true, NOW()),
    ('Elephant Gathering — Minneriya',
     'One of the largest gatherings of wild Asian elephants in the world. Hundreds of elephants congregate at Minneriya Tank.',
     'WILDLIFE', 'Minneriya', '2026-07-01'::date, '2026-09-30'::date, NULL, true, NOW()),
    ('Whale Watching Season — Mirissa',
     'Peak season for blue whale and sperm whale sightings off the southern coast of Sri Lanka. Best months November to April.',
     'WILDLIFE', 'Mirissa', '2026-11-01'::date, '2027-04-30'::date, NULL, true, NOW()),
    ('Arugam Bay Surf Season',
     'World-class surf season at Arugam Bay. Attracts international surfers. Main Point and Whiskey Point are top surf spots.',
     'SURF', 'Arugam Bay', '2026-05-01'::date, '2026-10-31'::date, NULL, true, NOW()),
    ('Galle Literary Festival',
     'International literary festival held inside the historic Galle Fort. Authors, speakers and cultural events.',
     'ENTERTAINMENT', 'Galle', '2026-01-20'::date, '2026-01-24'::date, NULL, true, NOW()),
    ('Colombo Food Festival',
     'Annual food festival showcasing Sri Lankan cuisine, street food, and international dishes in Colombo.',
     'FOOD', 'Colombo', '2026-03-15'::date, '2026-03-17'::date, NULL, true, NOW()),
    ('Southwest Monsoon',
     'Southwest monsoon brings heavy rainfall to western and southern coastal areas and hill country. Best to visit east coast during this period.',
     'MONSOON', 'West and South Coast', '2026-05-01'::date, '2026-09-30'::date, NULL, true, NOW()),
    ('Northeast Monsoon',
     'Northeast monsoon affects northern and eastern coastal areas. Best to visit west and south coast during this period.',
     'MONSOON', 'North and East Coast', '2026-10-01'::date, '2027-01-31'::date, NULL, true, NOW()),
    ('Diwali — Festival of Lights',
     'Hindu festival of lights celebrated by Tamil community across Sri Lanka with oil lamps, fireworks and sweets.',
     'RELIGIOUS', 'Island-wide', '2026-10-20'::date, '2026-10-20'::date, NULL, true, NOW()),
    ('Christmas in Galle Fort',
     'Unique Christmas celebrations inside the historic Galle Fort with decorations, events and festive markets.',
     'FESTIVAL', 'Galle', '2026-12-24'::date, '2026-12-26'::date, NULL, true, NOW()),
    ('Hikkaduwa Coral Festival',
     'Annual festival celebrating the coral reef ecosystem of Hikkaduwa. Snorkeling, diving events and beach activities.',
     'ENTERTAINMENT', 'Hikkaduwa', '2026-03-01'::date, '2026-03-03'::date, NULL, true, NOW())
) AS new_data (title, description, category, region,
    start_date, end_date, image_url, is_recurring, created_at)
WHERE NOT EXISTS (SELECT 1 FROM events LIMIT 1);



INSERT INTO hidden_gems (title, description, category, district,
    latitude, longitude, how_to_get_there, best_time, tips,
    approved, rating, review_count, created_at, updated_at)
SELECT * FROM (VALUES
    ('Jungle Beach',
     'A secluded beach near Unawatuna only accessible by boat or a jungle trek. Crystal clear water with no crowds.',
     'BEACH', 'Galle', 6.0089, 80.2491,
     'Take a boat from Unawatuna beach (10 min) or hike 30 min through jungle trail.',
     'November to April (dry season)', 'Bring snacks — no shops. Go early morning for calm water.',
     true, 4.8, 245, NOW(), NOW()),
    ('Hiriketiya Bay',
     'A horseshoe shaped bay hidden from the main road. Popular with surfers and digital nomads. Laid back vibe.',
     'BEACH', 'Matara', 5.9667, 80.5833,
     'From Dickwella town take a tuk-tuk heading south for 3km. Ask for Hiriketiya.',
     'October to April', 'Arrive before 8am for the best surf. Several good cafes nearby.',
     true, 4.7, 189, NOW(), NOW()),
    ('Ravana Ella Cave',
     'A lesser known cave near the Ravana Falls in Ella. According to legend this is where King Ravana kept Sita. Dramatic views.',
     'RUINS', 'Badulla', 6.8553, 81.0581,
     'From Ella town take the road towards Wellawaya. The cave is 2km from Ravana Falls — unmarked path on the right.',
     'January to August', 'Hire a local guide from Ella town for LKR 500. Wear good shoes.',
     true, 4.6, 134, NOW(), NOW()),
    ('Bambarakanda Waterfall',
     'Sri Lanka highest waterfall at 263 metres. Hidden in the Horton Plains region. Few tourists reach the base.',
     'WATERFALL', 'Nuwara Eliya', 6.7833, 80.8167,
     'Take the Haputale to Belihuloya road. Bambarakanda village is 3km off the main road. 45 min trek to base.',
     'March to May and October to November', 'Trek early morning before mist rolls in. Bring rain gear.',
     true, 4.9, 312, NOW(), NOW()),
    ('Yapahuwa Rock Fortress',
     'An ancient rock fortress rising 100 metres from the surrounding plain. Far less visited than Sigiriya but equally impressive.',
     'RUINS', 'Kurunegala', 7.8333, 80.3167,
     'Take the Colombo to Anuradhapura road. Turn at Maho junction — Yapahuwa is 10km from Maho.',
     'December to April', 'Arrive at opening time (7am) — you may have the whole place to yourself.',
     true, 4.5, 98, NOW(), NOW()),
    ('Ella Rock',
     'A challenging hike offering panoramic views of the Ella Gap and surrounding tea estates. More rewarding than Little Adams Peak.',
     'VIEWPOINT', 'Badulla', 6.8748, 81.0465,
     'Walk along the railway track from Ella station towards Demodara for 2km then follow the trail markers uphill.',
     'January to April', 'Start by 6am. Takes 3-4 hours return. No signboards — hire a guide.',
     true, 4.8, 421, NOW(), NOW()),
    ('Knuckles Cloud Forest',
     'A UNESCO designated cloud forest with unique biodiversity. Remote villages, leeches, mist and extraordinary scenery.',
     'VIEWPOINT', 'Matale', 7.4167, 80.8000,
     'From Kandy take the Matale road then turn towards Rattota. Arrange permits at the Forest Department office.',
     'February to April', 'Multi-day treks available. Register with the Forest Department. Leech socks essential.',
     true, 4.9, 167, NOW(), NOW()),
    ('Pigeon Island',
     'A tiny island near Trincomalee with some of Sri Lanka best coral reefs. Home to blacktip reef sharks.',
     'BEACH', 'Trincomalee', 8.5500, 81.2667,
     'Take a boat from Nilaveli Beach (10 min). Book through guesthouses in Nilaveli.',
     'April to September (east coast dry season)', 'Snorkeling only — no diving to protect coral. Bring underwater camera.',
     true, 4.7, 278, NOW(), NOW()),
    ('Mulkirigala Rock Temple',
     'A series of cave temples built into a dramatic granite outcrop. Far less visited than Dambulla but equally impressive.',
     'TEMPLE', 'Hambantota', 6.1167, 80.4667,
     'From Tangalle take the inland road towards Weeraketiya — Mulkirigala is 16km from Tangalle.',
     'Year round', 'Remove shoes before entering. Small entrance fee. Climb to the top for ocean views.',
     true, 4.6, 112, NOW(), NOW()),
    ('Pambahinna Village',
     'A traditional Sri Lankan village in the Knuckles range where time seems to have stopped. Homestays available.',
     'VILLAGE', 'Matale', 7.4500, 80.8333,
     'Arrange through Kandy guesthouses. 4WD vehicle required. 3 hour journey from Kandy.',
     'February to April', 'Book homestay in advance. Bring cash — no ATMs. Respect local customs.',
     true, 4.8, 56, NOW(), NOW()),
    ('Secret Tea Estate Cafe — Nuwara Eliya',
     'A hidden cafe inside a working tea estate with panoramic mountain views. Serves single origin tea picked that morning.',
     'CAFE', 'Nuwara Eliya', 6.9500, 80.7833,
     'Ask locals in Nuwara Eliya for the Lovers Leap estate road. 4km from town centre on an unmarked road.',
     'Year round — best during flush season March to May', 'No sign outside. Ring the bell. LKR 200 for tea and biscuits.',
     true, 4.9, 89, NOW(), NOW()),
    ('Udawatta Kele Forest Sanctuary',
     'A forgotten royal forest reserve in the heart of Kandy city. Ancient trees, monkeys and complete silence despite being central.',
     'VIEWPOINT', 'Kandy', 7.2967, 80.6414,
     'Enter from Kandy city centre near the Temple of the Tooth — follow signs to the forest reserve entrance.',
     'Year round', 'Enter before 8am for bird watching. Bring insect repellent. Carry water.',
     true, 4.4, 203, NOW(), NOW()),
    ('Rathnapura Gem Mines',
     'Visit a working traditional gem mine in the gem capital of Sri Lanka. Watch miners sift for sapphires and rubies.',
     'VILLAGE', 'Ratnapura', 6.6833, 80.4000,
     'From Ratnapura town hire a tuk-tuk to the Elapatha area — ask for gem pit visits.',
     'Year round — avoid monsoon May to September', 'Negotiate entry fee directly with mine owner. LKR 500-1000.',
     true, 4.5, 145, NOW(), NOW()),
    ('Mangrove Safari — Madu River',
     'A boat journey through a vast mangrove ecosystem near Balapitiya. Ancient temples on islands, monitor lizards and birds.',
     'VILLAGE', 'Galle', 6.2833, 80.0500,
     'Take the coastal road between Colombo and Galle. Balapitiya town is 90km from Colombo — boats leave from the river bank.',
     'November to April', 'Morning boats have best wildlife. 2 hour tour. Bargain the boat price.',
     true, 4.6, 334, NOW(), NOW()),
    ('Ambuluwawa Tower',
     'A unique biodiversity complex with a spiral tower on a mountain top offering 360 degree views across four provinces.',
     'VIEWPOINT', 'Kandy', 7.1833, 80.5833,
     'From Gampola town (20km from Kandy) take the road up Ambuluwawa mountain — 6km of winding road.',
     'Year round — clearest views December to April', 'Climb the narrow spiral tower for views. LKR 200 entry.',
     true, 4.7, 267, NOW(), NOW())
) AS new_data (title, description, category, district,
    latitude, longitude, how_to_get_there, best_time, tips,
    approved, rating, review_count, created_at, updated_at)
WHERE NOT EXISTS (SELECT 1 FROM hidden_gems LIMIT 1);

INSERT INTO tour_guides (full_name, bio, languages, specialties,
    district, price_per_day, verified, available,
    rating, review_count, phone, email,
    created_at, updated_at)
SELECT * FROM (VALUES
    ('Kamal Bandara',
     'Expert wildlife guide with 12 years experience in Yala and Wilpattu. Excellent tracker with deep knowledge of Sri Lanka wildlife.',
     'English,Sinhala', 'WILDLIFE,PHOTOGRAPHY',
     'Hambantota', 65.00, true, true, 4.9, 234,
     '+94771234567', 'kamal.guide@gmail.com', NOW(), NOW()),
    ('Priya Perera',
     'Cultural heritage specialist based in Kandy. Expert in Buddhist temples, Kandyan history and the Esala Perahera festival.',
     'English,Sinhala,Tamil', 'CULTURAL,FOOD',
     'Kandy', 45.00, true, true, 4.8, 189,
     '+94777654321', 'priya.guide@gmail.com', NOW(), NOW()),
    ('Roshan Fernando',
     'Professional surf instructor and coastal guide. Certified lifeguard. Based in Arugam Bay for 8 years.',
     'English,Sinhala', 'SURFING,WILDLIFE',
     'Ampara', 55.00, true, true, 4.7, 156,
     '+94712345678', 'roshan.surf@gmail.com', NOW(), NOW()),
    ('Amali Jayasinghe',
     'Ayurveda wellness guide and herbal medicine expert. Conducts authentic village ayurveda experiences near Galle.',
     'English,Sinhala', 'AYURVEDA,CULTURAL',
     'Galle', 40.00, true, true, 4.8, 98,
     '+94723456789', 'amali.ayur@gmail.com', NOW(), NOW()),
    ('Nimal Wickrama',
     'Expert trekking guide for Ella Rock, Knuckles Range and Adam''s Peak. First aid certified. 15 years experience.',
     'English,Sinhala,German', 'TREKKING,PHOTOGRAPHY',
     'Badulla', 50.00, true, true, 4.9, 312,
     '+94734567890', 'nimal.trek@gmail.com', NOW(), NOW()),
    ('Saman Rajapaksa',
     'Bird watching specialist with knowledge of over 400 Sri Lankan bird species. Regular guide at Sinharaja and Kitulgala.',
     'English,Sinhala', 'BIRDWATCHING,WILDLIFE',
     'Ratnapura', 55.00, true, true, 4.7, 87,
     '+94745678901', 'saman.birds@gmail.com', NOW(), NOW()),
    ('Dilini Cooray',
     'Food and cooking guide based in Colombo. Conducts Sri Lankan cooking classes and authentic street food tours.',
     'English,Sinhala,Tamil,French', 'FOOD,CULTURAL',
     'Colombo', 35.00, true, true, 4.6, 143,
     '+94756789012', 'dilini.food@gmail.com', NOW(), NOW()),
    ('Asanka Mendis',
     'Photography guide specialising in golden hour shoots at Sri Lanka top scenic spots. Professional photographer.',
     'English,Sinhala,Japanese', 'PHOTOGRAPHY,TREKKING',
     'Nuwara Eliya', 60.00, true, true, 4.8, 76,
     '+94767890123', 'asanka.photo@gmail.com', NOW(), NOW())
) AS new_data (full_name, bio, languages, specialties,
    district, price_per_day, verified, available,
    rating, review_count, phone, email,
    created_at, updated_at)
WHERE NOT EXISTS (SELECT 1 FROM tour_guides LIMIT 1);


INSERT INTO destinations (name, district, province, description,
    short_description, category, best_months, activities,
    latitude, longitude, cover_image_url, travel_time_from,
    entry_fee, opening_hours, featured, active,
    rating, review_count, unesco_status, created_at, updated_at)
SELECT * FROM (VALUES
    ('Sigiriya', 'Matale', 'Central Province',
     'Sigiriya or Lion Rock is an ancient rock fortress and palace ruin situated in the central Matale District. A UNESCO World Heritage Site rising 200 metres above the surrounding plains.',
     'Ancient rock fortress and UNESCO World Heritage Site rising 200m above the plains.',
     'HERITAGE', 'January,February,March,April,July,August,September',
     'hiking,history,photography,archaeology',
     7.9570, 80.7603, NULL,
     'Colombo:4h by road,Kandy:2h by road,Dambulla:20min by road',
     'USD 30 (foreigners), LKR 100 (locals)', '7:00 AM - 5:30 PM daily',
     true, true, 4.8, 1250, 'UNESCO World Heritage Site', NOW(), NOW()),
    ('Ella', 'Badulla', 'Uva Province',
     'Ella is a small town in the Badulla District surrounded by mountains and tea plantations. Famous for the Nine Arch Bridge, Ella Rock hike, and the scenic train journey from Kandy.',
     'Mountain town famous for scenic train rides, tea plantations and epic hikes.',
     'HILL', 'January,February,March,April,August,September',
     'hiking,photography,tea-tours,train-rides',
     6.8667, 81.0466, NULL,
     'Colombo:6h by road,Kandy:3h by train (scenic),Yala:3h by road',
     'Free (Ella Rock hike LKR 200)', 'Open all day',
     true, true, 4.7, 987, NULL, NOW(), NOW()),
    ('Kandy', 'Kandy', 'Central Province',
     'Kandy is the cultural capital of Sri Lanka and home to the famous Temple of the Tooth Relic. A UNESCO World Heritage Site. The annual Esala Perahera festival in August is one of the grandest processions in Asia.',
     'Cultural capital of Sri Lanka with the sacred Temple of the Tooth Relic.',
     'CULTURAL', 'January,February,March,July,August,December',
     'temples,cultural-shows,botanical-gardens,trekking',
     7.2906, 80.6337, NULL,
     'Colombo:3h by road or train,Sigiriya:2h by road,Ella:3h by train',
     'Temple: USD 15 (foreigners)', 'Open all day — Temple 5:30AM-8PM',
     true, true, 4.6, 1456, 'UNESCO World Heritage Site', NOW(), NOW()),
    ('Yala National Park', 'Hambantota', 'Southern Province',
     'Yala National Park is the most visited and second largest national park in Sri Lanka. It has the highest density of leopards in the world.',
     'World famous wildlife park with the highest leopard density on earth.',
     'WILDLIFE', 'February,March,April,May,June,July,August,September',
     'safari,wildlife,photography,birdwatching',
     6.3728, 81.5216, NULL,
     'Colombo:5h by road,Galle:3h by road,Ella:3h by road',
     'USD 25 per person + USD 15 vehicle (foreigners)', '6:00 AM - 6:00 PM (Block 1)',
     true, true, 4.9, 2341, NULL, NOW(), NOW()),
    ('Galle Fort', 'Galle', 'Southern Province',
     'Galle Fort is a UNESCO World Heritage Site built first in 1588 by the Portuguese and then extensively fortified by the Dutch during the 17th century.',
     'Historic Dutch colonial fort and UNESCO World Heritage Site on the southern coast.',
     'HERITAGE', 'November,December,January,February,March,April',
     'history,architecture,shopping,cafes,photography',
     6.0269, 80.2167, NULL,
     'Colombo:2h by road or train,Mirissa:30min by road',
     'Free to enter the fort', 'Open 24 hours',
     true, true, 4.7, 1876, 'UNESCO World Heritage Site', NOW(), NOW()),
    ('Mirissa', 'Matara', 'Southern Province',
     'Mirissa is a small town on the south coast of Sri Lanka known for its beautiful crescent-shaped beach and world-class whale watching.',
     'Beautiful crescent beach and the best whale watching destination in Sri Lanka.',
     'BEACH', 'November,December,January,February,March,April',
     'whale-watching,swimming,snorkeling,surfing,beach',
     5.9483, 80.4716, NULL,
     'Colombo:3h by road,Galle:30min by road',
     'Beach free. Whale watching USD 30-40', 'Open all day',
     true, true, 4.6, 1123, NULL, NOW(), NOW()),
    ('Arugam Bay', 'Ampara', 'Eastern Province',
     'Arugam Bay is internationally renowned as one of the top surfing destinations in the world. The Main Point surf break is famous among professional surfers.',
     'World-class surf destination on the east coast — international surfers paradise.',
     'SURF', 'May,June,July,August,September,October',
     'surfing,swimming,beach,elephant-safari',
     6.8403, 81.8362, NULL,
     'Colombo:8h by road,Ella:3h by road',
     'Beach free. Surf lessons USD 20-30', 'Open all day',
     true, true, 4.7, 876, NULL, NOW(), NOW()),
    ('Nuwara Eliya', 'Nuwara Eliya', 'Central Province',
     'Nuwara Eliya is a city in the tea country of central Sri Lanka nicknamed Little England due to its British colonial architecture.',
     'Hill station nicknamed Little England surrounded by tea estates and cool misty air.',
     'HILL', 'January,February,March,April',
     'tea-tours,hiking,horton-plains,photography,golf',
     6.9497, 80.7891, NULL,
     'Colombo:4h by road,Kandy:2.5h by road,Ella:2h by road',
     'Horton Plains: USD 25 (foreigners)', 'Open all day — Horton Plains 6AM-6PM',
     true, true, 4.5, 765, NULL, NOW(), NOW()),
    ('Trincomalee', 'Trincomalee', 'Eastern Province',
     'Trincomalee is a port city on the northeast coast known for one of the finest natural harbours in the world. Nilaveli and Uppuveli beaches offer crystal clear water.',
     'Pristine east coast beaches with world-class snorkeling at Pigeon Island.',
     'BEACH', 'April,May,June,July,August,September',
     'snorkeling,diving,swimming,whale-watching,temples',
     8.5874, 81.2152, NULL,
     'Colombo:6h by road,Sigiriya:3h by road',
     'Pigeon Island: USD 15 (foreigners)', 'Open all day',
     false, true, 4.6, 543, NULL, NOW(), NOW()),
    ('Anuradhapura', 'Anuradhapura', 'North Central Province',
     'Anuradhapura is one of the ancient capitals of Sri Lanka and is a UNESCO World Heritage Site. Contains the Sri Maha Bodhi tree — the oldest human-planted tree in the world.',
     'Ancient sacred city with 2500 year old bodhi tree and massive dagobas.',
     'CULTURAL', 'January,February,March,April,May,June,July,August',
     'history,temples,cycling,archaeology,pilgrimage',
     8.3114, 80.4037, NULL,
     'Colombo:4h by road,Sigiriya:1.5h by road',
     'USD 25 (foreigners)', '6:00 AM - 6:00 PM',
     false, true, 4.5, 654, 'UNESCO World Heritage Site', NOW(), NOW()),
    ('Polonnaruwa', 'Polonnaruwa', 'North Central Province',
     'Polonnaruwa is the second most ancient of Sri Lanka kingdoms. A UNESCO World Heritage Site with the Gal Vihara rock temple with magnificent Buddha statues carved from a single granite face.',
     'Ancient kingdom ruins with magnificent rock-carved Buddha statues.',
     'HERITAGE', 'January,February,March,April,May,June',
     'history,cycling,archaeology,photography',
     7.9403, 81.0188, NULL,
     'Colombo:5h by road,Sigiriya:1h by road',
     'USD 25 (foreigners)', '7:00 AM - 6:00 PM',
     false, true, 4.6, 432, 'UNESCO World Heritage Site', NOW(), NOW()),
    ('Jaffna', 'Jaffna', 'Northern Province',
     'Jaffna is the largest city in northern Sri Lanka with a distinct Tamil culture. Known for its unique cuisine, colorful Hindu temples and the historic Jaffna Fort.',
     'Culturally unique northern city with Tamil heritage, temples and island excursions.',
     'CULTURAL', 'May,June,July,August,September',
     'temples,history,island-tours,food,cycling',
     9.6615, 80.0255, NULL,
     'Colombo:8h by road or 1h by plane',
     'Fort: Free. Temples: nominal fee', 'Open all day',
     false, true, 4.4, 321, NULL, NOW(), NOW())
) AS new_data (name, district, province, description,
    short_description, category, best_months, activities,
    latitude, longitude, cover_image_url, travel_time_from,
    entry_fee, opening_hours, featured, active,
    rating, review_count, unesco_status, created_at, updated_at)
WHERE NOT EXISTS (SELECT 1 FROM destinations LIMIT 1);


INSERT INTO users (name, email, password, role, nationality, created_at, updated_at)
SELECT * FROM (VALUES
    ('Admin User',
     'admin@exploreceylon.com',
     '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.',
     'ADMIN',
     'Sri Lankan',
     NOW(), NOW()),
    ('Kamal Perera',
     'nimal@gmail.com',
     '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.',
     'TRAVELER',
     'Sri Lankan',
     NOW(), NOW()),
    ('supun Perera',
     'supun@gmail.com',
     '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.',
     'TRAVELER',
     'Sri Lankan',
     NOW(), NOW()),
    ('sadun Perera',
     'sadun@gmail.com',
     '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.',
     'TRAVELER',
     'India',
     NOW(), NOW())
) AS new_data (name, email, password, role, nationality, created_at, updated_at)
WHERE NOT EXISTS (SELECT 1 FROM users LIMIT 1);